language: java
sudo: required
install:
  - sudo apt-get install gnupg2
before_deploy:
  - mvn clean
  - echo $GPG_KEY > build.gpg
  - echo $M2_SETTINGS > .m2/settings.xml
  - gpg --import build.gpg
deploy:
  - provider: script
    script: mvn clean deploy -DaltDeploymentRepository=ossrh::default::file:///tmp/snapshot -Dgpg.skip
    on:
      branch: master
  - provider: script
    script: mvn clean verify gpg:sign install:install deploy:deploy -DaltDeploymentRepository=ossrh::default::file:///tmp/release -Dgpg.keyname=$GPG_KEYNAME
    on:
      tags: true
